version: "3.6"

# make sure to have a .env file in the same directory

services:
  libretime:
    image: odclive/libretime-docker:v0.1
    container_name: libretime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/libretime/airtime:/etc/airtime
      - ${USERDIR}/docker/libretime/stor:/srv/airtime/stor
      - ${USERDIR}/docker/libretime/watch:/srv/airtime/watch
      - libretime_postgres:/var/lib/postgresql/10/main
    ports:
      - 80:80
      - 8000:8000
    restart: always

volumes:
  libretime_postgres:
